<!DOCTYPE html>
<header>
    <nav>
        <ul>
            <li>
                <a href="https://emilieviot.sites.3wa.io/php/bre01-php-j2/require/index.php/?route=home">Accueil</a>
            </li>
            <li>
                <a href="https://emilieviot.sites.3wa.io/php/bre01-php-j2/require/index.php/?route=about">À propos</a>
            </li>
            <li>
                <a href="https://emilieviot.sites.3wa.io/php/bre01-php-j2/require/index.php/?route=contact">Contact</a>
            </li>
        </ul>
    </nav>
</header>